### ISSUE TITLE
1.1.0 Release

### ISSUE THREAD

**Issue by turboMaCk** [turboMaCk/glue#6]
Next release should contain changes from https://github.com/turboMaCk/glue/pull/5 and https://github.com/turboMaCk/glue/pull/4

### todo

- [x] Update README.md
- [x] Update documentation
- [x] Review API once again
- [x] Add built version of `./examples/Main.elm` to `./docs/index.html` (`./builddocs` script)
- [x] release 🚀

**Comment by turboMaCk** [comment]
https://github.com/turboMaCk/glue/releases/tag/1.1.0
